### ISSUE TITLE
Change data - more year options?

### ISSUE THREAD

**Issue by Gmangrove** [tbep-tech/landuse-change#1]
Could there be an option to change both ends (start and finish) of change analysis? Right now you can move the earlier year but 2017 is fixed, it would be good to be able & move both, especially with 2020 now online.

**Comment by fawda123** [comment]
@Gmangrove just added this feature, only issue is I can't show results for the proper change analysis if the second year is not 2020.  I would have to do the analysis for every year pair - not impossible, but not worth doing at this time.  The simple acreage summary tables work though
